server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      # Sigue habilitado el locator por si querÃ©s usar rutas automÃ¡ticas tipo
      # http://localhost:8080/servicio-contenedores/**, pero NO es obligatorio usarlo.
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        # ==============================
        #  ðŸŸ¦ SERVICIO CONTENEDORES
        #  Exponer:
        #    - /api/solicitudes/**
        #    - /api/contenedores/**
        # ==============================
        - id: servicio-contenedores
          uri: lb://servicio-contenedores
          predicates:
            - Path=/api/solicitudes/**,/api/contenedores/**

        # ==============================
        #  ðŸŸ© SERVICIO TRANSPORTE
        #  Exponer:
        #    - /api/rutas/**
        #    - /api/tramos/**
        #    - /api/camiones/**   (CRUD camiones)
        # ==============================
        - id: servicio-transporte
          uri: lb://servicio-transporte
          predicates:
            - Path=/api/rutas/**,/api/tramos/**,/api/camiones/**

        # ==============================
        #  ðŸŸ¨ SERVICIO TARIFA
        #  Exponer:
        #    - /api/tarifas/**
        # ==============================
        - id: servicio-tarifa
          uri: lb://servicio-tarifa
          predicates:
            - Path=/api/tarifas/**

        # ==============================
        #  ðŸŸ§ SERVICIO DEPOSITO
        #  Exponer:
        #    - /api/depositos/**
        # ==============================
        - id: servicio-deposito
          uri: lb://servicio-deposito
          predicates:
            - Path=/api/depositos/**

  security:
    oauth2:
      resourceserver:
        jwt:
          # Realm de Keycloak
          issuer-uri: http://localhost:8181/realms/tpi-realm
          jwk-set-uri: http://localhost:8181/realms/tpi-realm/protocol/openid-connect/certs

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.security: INFO
