server:
  port: 8082

spring:
  # SOLUCIÓN AL ERROR: Permite sobrescribir definiciones de beans duplicadas (e.g., Feign Clients)
  main:
    allow-bean-definition-overriding: true
    
  application:
    name: servicio-transporte

  # ==========================
  # BASE DE DATOS COMPARTIDA (H2 en archivo)
  # ==========================
  datasource:
    url: jdbc:h2:file:../h2/shared_db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # ==========================
  # CONFIGURACIÓN JPA (CORREGIDA)
  # ==========================
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true 
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        
    defer-datasource-initialization: true

  # ==========================
  # FORZAR EJECUCIÓN DE data.sql
  # ==========================
  sql:
    init:
      mode: always # Ejecuta siempre data.sql al iniciar

  # ==========================
  # H2 CONSOLE
  # ==========================
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/tpi-realm

# ==========================
# SWAGGER / OPENAPI
# ==========================
springdoc:
  api-docs:
    path: /api-docs 
  swagger-ui:
    path: /swagger-ui.html

# ==========================
# EUREKA CLIENT CONFIG
# ==========================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


osrm:
  base-url: http://localhost:5001