server:
  port: 8082   # Puerto del microservicio Transporte

spring:
  datasource:
    url: jdbc:h2:mem:logisticaDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true                   # Habilita consola web de H2
      path: /h2-console               # URL: http://localhost:8082/h2-console

springdoc:
  api-docs:
    path: /api-docs                   # URL del JSON con la documentaci√≥n OpenAPI
  swagger-ui:
    path: /swagger-ui.html            # URL de Swagger UI

