server:
  port: 8082  # Puerto del microservicio DepÃ³sito

spring:
  application:
    name: servicio-deposito

  datasource:
    # ðŸ”¹ Misma base H2 compartida entre microservicios
    url: jdbc:h2:mem:logisticaDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: update          # Solo para desarrollo; en prod usar Flyway
    properties:
      hibernate:
        format_sql: true
        show_sql: false
    open-in-view: false

  h2:
    console:
      enabled: true
      path: /h2-console          # URL: http://localhost:8082/h2-console

springdoc:
  api-docs:
    path: /api-docs              # JSON de OpenAPI
  swagger-ui:
    path: /swagger-ui.html       # Swagger UI
