# ==========================
# PUERTO DE ESTE MICROSERVICIO
# ==========================
server:
  port: 8081

spring:
  application:
    name: servicio-contenedores

  # ==========================
  # BASE DE DATOS COMPARTIDA
  # ==========================
  datasource:
    # Apunta a un archivo en la carpeta 'h2' del directorio raíz
    url: jdbc:h2:file:../h2/shared_db;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # ==========================
  # CONFIGURACIÓN JPA
  # ==========================
  jpa:
    # 'update' es clave: crea las tablas si no existen, pero no borra datos
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true

  # ==========================
  # H2 CONSOLE
  # ==========================
  h2:
    console:
      enabled: true
      path: /h2-console
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/tpi-realm
          # opcional (mejora velocidad)
          # jwk-set-uri: http://localhost:8181/realms/tpi-realm/protocol/openid-connect/certs

# ==========================
# CONFIGURACIÓN DE EUREKA CLIENT
# ==========================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/


